from typing import Any


def exercise(
    name: str,
    movement_pattern: str,
    exercise_category: str,
    prescription_type: str,
    equipment: str,
    modality: str,
    fatigue_cost: str,
    combat_transfer: str,
    difficulty: str,
    joint_stress: str,
    default_sets: int,
    reps_min: int,
    reps_max: int,
    target_rpe: float,
    notes: str,
    tags: list[str] | None = None,
    duration_minutes: int | None = None,
    hold_seconds: int | None = None,
    distance: str = "",
    heart_rate_target: str = "",
    intensity_target: str = "",
    side: str = "",
    session_slot: str = "",
    method_tag: str = "",
    body_region: str = "",
    mobility_style: str = "",
    substitution_group: str = "",
    modality_group: str = "",
    progression_style: str = "",
    fatigue_points: int = 3,
    technical_transfer: str = "medium",
    coaching_cues: str = "",
) -> dict[str, Any]:
    return {
        "exercise_name": name,
        "movement_pattern": movement_pattern,
        "exercise_category": exercise_category,
        "prescription_type": prescription_type,
        "equipment": equipment,
        "modality": modality,
        "fatigue_cost": fatigue_cost,
        "combat_transfer": combat_transfer,
        "difficulty": difficulty,
        "joint_stress": joint_stress,
        "planned_sets": default_sets,
        "planned_reps_min": reps_min,
        "planned_reps_max": reps_max,
        "planned_weight": 0,
        "target_rpe": target_rpe,
        "notes": notes,
        "tags": tags or [],
        "duration_minutes": duration_minutes,
        "hold_seconds": hold_seconds,
        "distance": distance,
        "heart_rate_target": heart_rate_target,
        "intensity_target": intensity_target,
        "side": side,
        "session_slot": session_slot,
        "method_tag": method_tag,
        "body_region": body_region,
        "mobility_style": mobility_style,
        "substitution_group": substitution_group,
        "modality_group": modality_group,
        "progression_style": progression_style,
        "fatigue_points": fatigue_points,
        "technical_transfer": technical_transfer,
        "coaching_cues": coaching_cues,
    }


EXERCISE_CATALOG = [
    # -------------------------------------------------------------------------
    # Main strength / submax strength
    # -------------------------------------------------------------------------
    exercise(
        "Trap Bar Deadlift",
        "hinge",
        "main_lift",
        "strength",
        "trap bar",
        "free weight",
        "high",
        "high",
        "high",
        "medium",
        3,
        3,
        5,
        8.0,
        "Main hinge strength. Smooth reps only.",
        ["posterior_chain", "grappling", "strength"],
        session_slot="main_strength",
        method_tag="submax_strength",
        body_region="posterior_chain",
        substitution_group="hinge_strength",
        modality_group="free_weight_hinge",
        progression_style="load_progression",
        fatigue_points=8,
        technical_transfer="high",
        coaching_cues="Brace hard, push the floor away, and stop sets before form degrades.",
    ),
    exercise(
        "Bench Press",
        "horizontal_push",
        "main_lift",
        "strength",
        "barbell",
        "free weight",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        4,
        6,
        8.0,
        "Main press. Do not grind reps.",
        ["upper", "strength", "press"],
        session_slot="main_strength",
        method_tag="submax_strength",
        body_region="upper_push",
        substitution_group="horizontal_push_strength",
        modality_group="barbell_press",
        progression_style="load_progression",
        fatigue_points=6,
        technical_transfer="medium",
        coaching_cues="Shoulders packed, stable feet, controlled descent, powerful press.",
    ),
    exercise(
        "Squat",
        "squat",
        "main_lift",
        "strength",
        "barbell",
        "free weight",
        "high",
        "high",
        "high",
        "high",
        3,
        4,
        6,
        8.0,
        "Main squat pattern. Keep positions clean.",
        ["lower", "strength"],
        session_slot="main_strength",
        method_tag="submax_strength",
        body_region="lower",
        substitution_group="squat_strength",
        modality_group="barbell_squat",
        progression_style="load_progression",
        fatigue_points=8,
        technical_transfer="medium",
        coaching_cues="Brace before descent, control depth, and drive evenly through the floor.",
    ),
    exercise(
        "Weighted Pull-Up",
        "vertical_pull",
        "main_lift",
        "strength",
        "pull-up bar",
        "weighted bodyweight",
        "high",
        "high",
        "high",
        "medium",
        3,
        3,
        6,
        8.0,
        "Added weight only. Prioritize clean reps.",
        ["upper", "grip", "grappling", "pull"],
        session_slot="main_strength",
        method_tag="submax_strength",
        body_region="upper_pull",
        substitution_group="vertical_pull_strength",
        modality_group="weighted_bodyweight_pull",
        progression_style="load_progression",
        fatigue_points=7,
        technical_transfer="high",
        coaching_cues="Start from a dead hang, pull chest toward bar, and avoid kicking.",
    ),
    exercise(
        "Weighted Chin-Up",
        "vertical_pull",
        "main_lift",
        "strength",
        "pull-up bar",
        "weighted bodyweight",
        "high",
        "high",
        "high",
        "medium",
        3,
        3,
        6,
        8.0,
        "Added weight only. Chin-up variation for pulling strength.",
        ["upper", "grip", "grappling", "pull"],
        session_slot="main_strength",
        method_tag="submax_strength",
        body_region="upper_pull",
        substitution_group="vertical_pull_strength",
        modality_group="weighted_bodyweight_pull",
        progression_style="load_progression",
        fatigue_points=7,
        technical_transfer="high",
        coaching_cues="Pull elbows down, keep ribs controlled, and finish with strong scapular depression.",
    ),

    # -------------------------------------------------------------------------
    # Overcoming isometrics
    # -------------------------------------------------------------------------
    exercise(
        "Overcoming Isometric Mid-Thigh Pull",
        "hinge",
        "secondary_lift",
        "isometric",
        "barbell pins or immovable setup",
        "overcoming isometric",
        "medium",
        "high",
        "high",
        "medium",
        4,
        3,
        6,
        8.5,
        "Pull maximally against immovable pins. High intent, short duration, full rest.",
        ["posterior_chain", "isometric", "strength", "grappling"],
        hold_seconds=5,
        session_slot="lower_isometric_strength",
        method_tag="overcoming_isometric",
        body_region="posterior_chain",
        substitution_group="hinge_strength",
        modality_group="isometric_hinge",
        progression_style="intent_progression",
        fatigue_points=5,
        technical_transfer="high",
        coaching_cues="Ramp tension quickly, push through the floor, and keep position locked.",
    ),
    exercise(
        "Overcoming Isometric Split Squat",
        "single_leg",
        "secondary_lift",
        "isometric",
        "pins, straps, or immovable object",
        "overcoming isometric",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        3,
        6,
        8.0,
        "Drive upward against an immovable setup from a strong split-squat position.",
        ["lower", "single_leg", "isometric"],
        hold_seconds=5,
        side="each side",
        session_slot="lower_isometric_strength",
        method_tag="overcoming_isometric",
        body_region="lower",
        substitution_group="single_leg_strength",
        modality_group="isometric_single_leg",
        progression_style="intent_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Own the position first, then ramp force without twisting.",
    ),
    exercise(
        "Overcoming Isometric Bench Press",
        "horizontal_push",
        "secondary_lift",
        "isometric",
        "barbell pins",
        "overcoming isometric",
        "medium",
        "medium",
        "medium",
        "medium",
        4,
        3,
        6,
        8.5,
        "Press maximally into immovable pins. Useful for strength exposure without high volume.",
        ["upper", "press", "isometric"],
        hold_seconds=5,
        session_slot="upper_isometric_strength",
        method_tag="overcoming_isometric",
        body_region="upper_push",
        substitution_group="horizontal_push_strength",
        modality_group="isometric_press",
        progression_style="intent_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Set shoulders, drive feet, and press hard without losing position.",
    ),
    exercise(
        "Overcoming Isometric Row",
        "horizontal_pull",
        "secondary_lift",
        "isometric",
        "barbell pins, straps, or immovable handle",
        "overcoming isometric",
        "medium",
        "high",
        "medium",
        "low",
        4,
        3,
        6,
        8.0,
        "Pull against an immovable setup. Excellent for upper-back and grappling strength.",
        ["upper", "grappling", "pull", "isometric"],
        hold_seconds=5,
        session_slot="upper_isometric_strength",
        method_tag="overcoming_isometric",
        body_region="upper_pull",
        substitution_group="horizontal_pull_strength",
        modality_group="isometric_pull",
        progression_style="intent_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Pull elbows back, squeeze upper back, and keep ribs down.",
    ),
    exercise(
        "Wall Push Isometric",
        "horizontal_push",
        "accessory",
        "isometric",
        "wall",
        "overcoming isometric",
        "low",
        "medium",
        "low",
        "low",
        3,
        5,
        10,
        6.5,
        "Push hard into a wall without losing posture. Low setup cost and joint-friendly.",
        ["upper", "press", "isometric", "light"],
        hold_seconds=8,
        session_slot="upper_isometric_strength",
        method_tag="overcoming_isometric",
        body_region="upper_push",
        substitution_group="horizontal_push_strength",
        modality_group="bodyweight_isometric",
        progression_style="intent_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Brace, press progressively, and avoid shrugging.",
    ),
    exercise(
        "Towel Row Isometric",
        "horizontal_pull",
        "accessory",
        "isometric",
        "towel",
        "overcoming isometric",
        "low",
        "high",
        "low",
        "low",
        3,
        5,
        10,
        7.0,
        "Pull hard against a towel setup. Good for grip, lats, and upper-back intent.",
        ["upper", "grip", "grappling", "isometric"],
        hold_seconds=8,
        session_slot="upper_isometric_strength",
        method_tag="overcoming_isometric",
        body_region="upper_pull",
        substitution_group="horizontal_pull_strength",
        modality_group="bodyweight_isometric",
        progression_style="intent_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Pull apart and back, squeeze shoulder blades, and keep neck relaxed.",
    ),

    # -------------------------------------------------------------------------
    # Squat pattern substitutions
    # -------------------------------------------------------------------------
    exercise(
        "Hack Squat",
        "squat",
        "secondary_lift",
        "strength",
        "machine",
        "machine",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        8,
        12,
        7.5,
        "Squat pattern with more external stability.",
        ["lower", "modality_swap"],
        session_slot="supplemental_strength",
        method_tag="repeated_effort",
        body_region="lower",
        substitution_group="squat_strength",
        modality_group="machine_squat",
        progression_style="rep_progression",
        fatigue_points=5,
        technical_transfer="medium",
        coaching_cues="Control depth, keep knees tracking, and avoid bouncing.",
    ),
    exercise(
        "Leg Press",
        "squat",
        "secondary_lift",
        "strength",
        "machine",
        "machine",
        "medium",
        "medium",
        "low",
        "medium",
        3,
        10,
        15,
        7.5,
        "Lower-body volume with less bracing demand.",
        ["lower", "modality_swap"],
        session_slot="supplemental_strength",
        method_tag="repeated_effort",
        body_region="lower",
        substitution_group="squat_strength",
        modality_group="machine_squat",
        progression_style="rep_progression",
        fatigue_points=5,
        technical_transfer="low",
        coaching_cues="Use controlled range and keep pelvis stable.",
    ),
    exercise(
        "Zercher Squat",
        "squat",
        "secondary_lift",
        "strength",
        "barbell",
        "free weight",
        "high",
        "high",
        "high",
        "medium",
        3,
        5,
        8,
        7.5,
        "Squat variation with trunk and upper-back demand.",
        ["lower", "grappling", "modality_swap"],
        session_slot="supplemental_strength",
        method_tag="special_exercise",
        body_region="lower",
        substitution_group="squat_strength",
        modality_group="barbell_squat",
        progression_style="rep_progression",
        fatigue_points=7,
        technical_transfer="high",
        coaching_cues="Keep elbows high, brace hard, and avoid collapsing forward.",
    ),
    exercise(
        "Front Squat",
        "squat",
        "secondary_lift",
        "strength",
        "barbell",
        "free weight",
        "high",
        "medium",
        "high",
        "medium",
        3,
        4,
        8,
        7.5,
        "Upright squat variation. Keep it technical.",
        ["lower", "modality_swap"],
        session_slot="supplemental_strength",
        method_tag="special_exercise",
        body_region="lower",
        substitution_group="squat_strength",
        modality_group="barbell_squat",
        progression_style="rep_progression",
        fatigue_points=7,
        technical_transfer="medium",
        coaching_cues="Elbows up, ribs down, and drive tall out of the bottom.",
    ),
    exercise(
        "Goblet Squat",
        "squat",
        "accessory",
        "strength",
        "dumbbell or kettlebell",
        "free weight",
        "low",
        "medium",
        "low",
        "low",
        3,
        8,
        12,
        6.5,
        "Light squat pattern. Good for lower-readiness days.",
        ["lower", "light"],
        session_slot="low_fatigue_lower",
        method_tag="repeated_effort",
        body_region="lower",
        substitution_group="squat_strength",
        modality_group="db_kb_squat",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Stay tall, sit between hips, and keep reps smooth.",
    ),

    # -------------------------------------------------------------------------
    # Hinge / posterior-chain
    # -------------------------------------------------------------------------
    exercise(
        "Romanian Deadlift",
        "hinge",
        "secondary_lift",
        "strength",
        "barbell or dumbbells",
        "free weight",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        6,
        10,
        7.5,
        "Hamstrings, glutes, and trunk tension.",
        ["posterior_chain", "grappling"],
        session_slot="posterior_chain_accessory",
        method_tag="repeated_effort",
        body_region="posterior_chain",
        substitution_group="hinge_strength",
        modality_group="free_weight_hinge",
        progression_style="rep_progression",
        fatigue_points=6,
        technical_transfer="high",
        coaching_cues="Hips back, soft knees, long spine, and own the eccentric.",
    ),
    exercise(
        "Barbell Hip Thrust",
        "hinge",
        "secondary_lift",
        "strength",
        "barbell",
        "free weight",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        8,
        12,
        7.5,
        "Glute strength without as much spinal fatigue.",
        ["posterior_chain", "modality_swap"],
        session_slot="posterior_chain_accessory",
        method_tag="repeated_effort",
        body_region="glutes",
        substitution_group="hinge_strength",
        modality_group="hip_extension",
        progression_style="rep_progression",
        fatigue_points=5,
        technical_transfer="medium",
        coaching_cues="Posteriorly tilt pelvis at the top and avoid overextending the low back.",
    ),
    exercise(
        "Barbell Glute Bridge",
        "hinge",
        "accessory",
        "strength",
        "barbell",
        "free weight",
        "low",
        "medium",
        "low",
        "low",
        4,
        10,
        12,
        7.0,
        "Glute-focused bridge work with low systemic fatigue.",
        ["posterior_chain", "glutes", "accessory"],
        session_slot="posterior_chain_accessory",
        method_tag="repeated_effort",
        body_region="glutes",
        substitution_group="hinge_strength",
        modality_group="hip_extension",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Drive through heels, squeeze glutes, and keep ribs down.",
    ),
    exercise(
        "Kettlebell Swing",
        "hinge",
        "gpp",
        "conditioning",
        "kettlebell",
        "ballistic",
        "medium",
        "high",
        "medium",
        "medium",
        4,
        10,
        20,
        7.0,
        "Explosive hinge conditioning. Keep reps crisp.",
        ["posterior_chain", "athletic", "conditioning"],
        session_slot="dynamic_effort",
        method_tag="dynamic_effort",
        body_region="posterior_chain",
        substitution_group="hinge_power",
        modality_group="ballistic_hinge",
        progression_style="density_progression",
        fatigue_points=5,
        technical_transfer="high",
        coaching_cues="Snap hips, keep arms relaxed, and stop before technique gets loose.",
    ),
    exercise(
        "Back Extension",
        "posterior_chain",
        "accessory",
        "bodyweight",
        "back extension bench",
        "bodyweight or loaded",
        "medium",
        "high",
        "medium",
        "low",
        3,
        10,
        15,
        7.0,
        "Posterior-chain support and low-back endurance.",
        ["posterior_chain", "grappling"],
        session_slot="posterior_chain_accessory",
        method_tag="repeated_effort",
        body_region="posterior_chain",
        substitution_group="posterior_chain_accessory",
        modality_group="bodyweight_posterior_chain",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Move from hips, squeeze glutes, and avoid hyperextending.",
    ),
    exercise(
        "Bodyweight 45-Degree Hyper",
        "posterior_chain",
        "accessory",
        "bodyweight",
        "45-degree hyper",
        "bodyweight",
        "low",
        "medium",
        "low",
        "low",
        3,
        20,
        30,
        6.5,
        "High-rep posterior-chain blood flow.",
        ["posterior_chain", "glutes", "recovery"],
        session_slot="posterior_chain_blood_flow",
        method_tag="repeated_effort",
        body_region="posterior_chain",
        substitution_group="posterior_chain_accessory",
        modality_group="bodyweight_posterior_chain",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Round upper back slightly if glute focus is desired, then drive hips into pad.",
    ),
    exercise(
        "Reverse Hyper",
        "posterior_chain",
        "accessory",
        "strength",
        "reverse hyper machine",
        "machine",
        "low",
        "medium",
        "low",
        "low",
        3,
        12,
        20,
        6.5,
        "Posterior-chain blood flow and low-back support.",
        ["posterior_chain", "recovery"],
        session_slot="posterior_chain_blood_flow",
        method_tag="repeated_effort",
        body_region="posterior_chain",
        substitution_group="posterior_chain_accessory",
        modality_group="machine_posterior_chain",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Use controlled swing, squeeze glutes, and do not crank the low back.",
    ),
    exercise(
        "Hamstring Curl",
        "posterior_chain",
        "accessory",
        "strength",
        "machine",
        "machine",
        "low",
        "medium",
        "low",
        "low",
        3,
        10,
        15,
        7.0,
        "Hamstring isolation with low systemic fatigue.",
        ["posterior_chain", "accessory"],
        session_slot="posterior_chain_accessory",
        method_tag="repeated_effort",
        body_region="hamstrings",
        substitution_group="hamstring_accessory",
        modality_group="machine_isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="low",
        coaching_cues="Control the eccentric and squeeze the curl hard.",
    ),
    exercise(
        "Frog Pump",
        "hinge",
        "accessory",
        "bodyweight",
        "floor",
        "bodyweight",
        "low",
        "low",
        "low",
        "low",
        3,
        30,
        50,
        6.5,
        "Glute pump accessory with very low systemic fatigue.",
        ["glutes", "accessory", "pump"],
        session_slot="posterior_chain_blood_flow",
        method_tag="repeated_effort",
        body_region="glutes",
        substitution_group="glute_accessory",
        modality_group="bodyweight_glute",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="low",
        coaching_cues="Soles together, knees out, short range, hard glute squeeze.",
    ),
    exercise(
        "Side-Lying Hip Abduction",
        "hip_accessory",
        "accessory",
        "bodyweight",
        "floor",
        "bodyweight",
        "low",
        "medium",
        "low",
        "low",
        3,
        15,
        25,
        6.5,
        "Glute medius accessory for hip control.",
        ["glutes", "hips", "accessory"],
        side="each side",
        session_slot="hip_accessory",
        method_tag="repeated_effort",
        body_region="hips",
        substitution_group="hip_accessory",
        modality_group="bodyweight_glute",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Keep pelvis stacked and raise from the side hip, not the low back.",
    ),
    exercise(
        "Cable Hip External Rotation",
        "hip_accessory",
        "accessory",
        "strength",
        "cable",
        "cable",
        "low",
        "medium",
        "low",
        "low",
        3,
        10,
        15,
        6.5,
        "Hip external rotation strength for usable hip control.",
        ["hips", "glutes", "accessory"],
        side="each side",
        session_slot="hip_accessory",
        method_tag="repeated_effort",
        body_region="hips",
        substitution_group="hip_accessory",
        modality_group="cable_hip",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Move slowly and keep the pelvis quiet.",
    ),

    # -------------------------------------------------------------------------
    # Upper push
    # -------------------------------------------------------------------------
    exercise(
        "DB Bench Press",
        "horizontal_push",
        "secondary_lift",
        "strength",
        "dumbbells",
        "free weight",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        8,
        12,
        7.5,
        "Pressing volume with more freedom than barbell bench.",
        ["upper", "press", "modality_swap"],
        session_slot="supplemental_strength",
        method_tag="repeated_effort",
        body_region="upper_push",
        substitution_group="horizontal_push_strength",
        modality_group="db_press",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Control the bottom, press evenly, and keep shoulder blades stable.",
    ),
    exercise(
        "Incline DB Bench",
        "horizontal_push",
        "secondary_lift",
        "strength",
        "dumbbells",
        "free weight",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        8,
        12,
        7.5,
        "Incline pressing for upper chest and shoulders.",
        ["upper", "press"],
        session_slot="supplemental_strength",
        method_tag="repeated_effort",
        body_region="upper_push",
        substitution_group="horizontal_push_strength",
        modality_group="db_press",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Keep ribs down and press without shrugging.",
    ),
    exercise(
        "Push-Up",
        "horizontal_push",
        "accessory",
        "bodyweight",
        "floor",
        "bodyweight",
        "low",
        "medium",
        "low",
        "low",
        3,
        10,
        20,
        7.0,
        "Bodyweight pressing volume.",
        ["upper", "press", "light"],
        session_slot="low_fatigue_upper",
        method_tag="repeated_effort",
        body_region="upper_push",
        substitution_group="horizontal_push_strength",
        modality_group="bodyweight_press",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Keep a straight line from head to heel and finish with strong lockout.",
    ),
    exercise(
        "Landmine Press",
        "vertical_push",
        "secondary_lift",
        "strength",
        "landmine",
        "free weight",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        6,
        10,
        7.5,
        "Athletic pressing without excessive shoulder stress.",
        ["upper", "press", "athletic"],
        session_slot="supplemental_strength",
        method_tag="repeated_effort",
        body_region="upper_push",
        substitution_group="vertical_push_strength",
        modality_group="landmine_press",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Press up and slightly forward, reach at the top, and keep trunk braced.",
    ),
    exercise(
        "DB Shoulder Press",
        "vertical_push",
        "secondary_lift",
        "strength",
        "dumbbells",
        "free weight",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        8,
        12,
        7.5,
        "Vertical pressing volume.",
        ["upper", "press"],
        session_slot="supplemental_strength",
        method_tag="repeated_effort",
        body_region="upper_push",
        substitution_group="vertical_push_strength",
        modality_group="db_press",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Press smoothly and avoid turning it into a low-back extension.",
    ),
    exercise(
        "Lateral Raise",
        "shoulder_accessory",
        "accessory",
        "strength",
        "dumbbells or cable",
        "isolation",
        "low",
        "low",
        "low",
        "low",
        3,
        12,
        20,
        7.0,
        "Shoulder accessory for delts.",
        ["shoulders", "accessory", "pump"],
        session_slot="shoulder_accessory",
        method_tag="repeated_effort",
        body_region="shoulders",
        substitution_group="shoulder_accessory",
        modality_group="isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="low",
        coaching_cues="Lead with elbows and stop before shrugging takes over.",
    ),
    exercise(
        "Face Pull",
        "shoulder_accessory",
        "accessory",
        "strength",
        "cable or band",
        "cable",
        "low",
        "medium",
        "low",
        "low",
        3,
        12,
        20,
        6.5,
        "Rear delt and shoulder health.",
        ["shoulders", "upper_back", "recovery"],
        session_slot="shoulder_accessory",
        method_tag="repeated_effort",
        body_region="shoulders",
        substitution_group="shoulder_accessory",
        modality_group="cable",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Pull toward forehead and rotate thumbs back.",
    ),

    # -------------------------------------------------------------------------
    # Upper pull
    # -------------------------------------------------------------------------
    exercise(
        "Chest-Supported Row",
        "horizontal_pull",
        "secondary_lift",
        "strength",
        "machine or bench + dumbbells",
        "supported pull",
        "medium",
        "high",
        "medium",
        "low",
        3,
        8,
        12,
        8.0,
        "Upper-back strength without taxing the low back.",
        ["upper", "grappling", "posture"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="horizontal_pull_strength",
        modality_group="supported_pull",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Pull elbows back, pause briefly, and keep chest supported.",
    ),
    exercise(
        "DB Row",
        "horizontal_pull",
        "accessory",
        "strength",
        "dumbbell",
        "free weight",
        "medium",
        "high",
        "medium",
        "low",
        3,
        8,
        12,
        8.0,
        "Rowing volume for lats and upper back.",
        ["upper", "grappling"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="horizontal_pull_strength",
        modality_group="free_weight_pull",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Reach long at the bottom and pull elbow toward hip.",
    ),
    exercise(
        "Cable Row",
        "horizontal_pull",
        "accessory",
        "strength",
        "cable machine",
        "machine",
        "low",
        "medium",
        "low",
        "low",
        3,
        10,
        15,
        7.0,
        "Low-fatigue rowing volume.",
        ["upper", "modality_swap"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="horizontal_pull_strength",
        modality_group="machine_pull",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Keep ribs down, pull through elbows, and control the return.",
    ),
    exercise(
        "Seal Row",
        "horizontal_pull",
        "secondary_lift",
        "strength",
        "bench + barbell/dumbbells",
        "supported pull",
        "medium",
        "high",
        "medium",
        "low",
        3,
        8,
        12,
        7.5,
        "Strict upper-back row.",
        ["upper", "grappling"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="horizontal_pull_strength",
        modality_group="supported_pull",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Stay strict and pause at the top without lifting the chest.",
    ),
    exercise(
        "Pull-Up",
        "vertical_pull",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        5,
        10,
        8.0,
        "Bodyweight pulling volume.",
        ["upper", "grip", "grappling"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="vertical_pull_strength",
        modality_group="bodyweight_pull",
        progression_style="rep_progression",
        fatigue_points=5,
        technical_transfer="high",
        coaching_cues="Use clean reps and stop before kipping or reaching with the neck.",
    ),
    exercise(
        "Chin-Up",
        "vertical_pull",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        5,
        10,
        8.0,
        "Bodyweight pulling with more biceps involvement.",
        ["upper", "grip", "grappling"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="vertical_pull_strength",
        modality_group="bodyweight_pull",
        progression_style="rep_progression",
        fatigue_points=5,
        technical_transfer="high",
        coaching_cues="Drive elbows down and finish strong without swinging.",
    ),
    exercise(
        "Neutral-Grip Pull-Up",
        "vertical_pull",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "high",
        "medium",
        "low",
        3,
        5,
        10,
        7.5,
        "Joint-friendly vertical pull variation.",
        ["upper", "grip", "grappling"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="vertical_pull_strength",
        modality_group="bodyweight_pull",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Pull smoothly and keep shoulders packed.",
    ),
    exercise(
        "Lat Pulldown",
        "vertical_pull",
        "accessory",
        "strength",
        "cable machine",
        "machine",
        "low",
        "medium",
        "low",
        "low",
        3,
        8,
        12,
        7.0,
        "Vertical pull substitution when pull-ups are not ideal.",
        ["upper", "modality_swap"],
        session_slot="upper_back_accessory",
        method_tag="repeated_effort",
        body_region="upper_pull",
        substitution_group="vertical_pull_strength",
        modality_group="machine_pull",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Pull elbows down and avoid leaning way back.",
    ),

    # -------------------------------------------------------------------------
    # Single-leg / lower accessories
    # -------------------------------------------------------------------------
    exercise(
        "Step-Up",
        "single_leg",
        "accessory",
        "strength",
        "box + dumbbells optional",
        "single-leg",
        "medium",
        "medium",
        "medium",
        "low",
        2,
        8,
        12,
        7.0,
        "Single-leg strength and balance.",
        ["lower", "single_leg"],
        session_slot="single_leg_strength",
        method_tag="repeated_effort",
        body_region="lower",
        substitution_group="single_leg_strength",
        modality_group="single_leg",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Drive through the working leg and avoid bouncing off the back foot.",
    ),
    exercise(
        "Split Squat",
        "single_leg",
        "accessory",
        "strength",
        "dumbbells optional",
        "single-leg",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        8,
        12,
        7.5,
        "Single-leg strength with trunk control.",
        ["lower", "single_leg"],
        session_slot="single_leg_strength",
        method_tag="repeated_effort",
        body_region="lower",
        substitution_group="single_leg_strength",
        modality_group="single_leg",
        progression_style="rep_progression",
        fatigue_points=5,
        technical_transfer="medium",
        coaching_cues="Stay tall, control depth, and keep pressure through the front foot.",
    ),
    exercise(
        "Reverse Lunge",
        "single_leg",
        "accessory",
        "strength",
        "dumbbells optional",
        "single-leg",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        8,
        12,
        7.0,
        "Single-leg work with controlled fatigue.",
        ["lower", "single_leg"],
        session_slot="single_leg_strength",
        method_tag="repeated_effort",
        body_region="lower",
        substitution_group="single_leg_strength",
        modality_group="single_leg",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Step back softly and drive through the front leg.",
    ),
    exercise(
        "Cossack Squat",
        "single_leg",
        "accessory",
        "mobility",
        "bodyweight or kettlebell",
        "mobility strength",
        "low",
        "medium",
        "medium",
        "low",
        2,
        5,
        8,
        5.0,
        "Lateral hip mobility and leg strength.",
        ["hips", "mobility", "single_leg"],
        side="each side",
        intensity_target="controlled range",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="dynamic_mobility",
        substitution_group="hip_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Move slowly, keep heel down, and only use range you control.",
    ),

    # -------------------------------------------------------------------------
    # Carries / grip / GPP
    # -------------------------------------------------------------------------
    exercise(
        "Farmer Carry",
        "carry_grip",
        "gpp",
        "carry",
        "dumbbells or kettlebells",
        "loaded carry",
        "medium",
        "high",
        "medium",
        "low",
        3,
        30,
        60,
        7.5,
        "Grip, trunk, and posture.",
        ["grip", "gpp", "grappling"],
        distance="30-60 sec",
        session_slot="grip_gpp",
        method_tag="gpp",
        body_region="grip_core",
        substitution_group="loaded_carry",
        modality_group="loaded_carry",
        progression_style="time_or_load_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Walk tall, crush the handles, and keep ribs stacked over pelvis.",
    ),
    exercise(
        "Suitcase Carry",
        "carry_grip",
        "gpp",
        "carry",
        "dumbbell or kettlebell",
        "loaded carry",
        "medium",
        "high",
        "medium",
        "low",
        3,
        30,
        60,
        7.0,
        "Anti-lateral flexion and grip.",
        ["grip", "core", "gpp"],
        distance="30-60 sec each side",
        side="each side",
        session_slot="grip_gpp",
        method_tag="gpp",
        body_region="grip_core",
        substitution_group="loaded_carry",
        modality_group="loaded_carry",
        progression_style="time_or_load_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Do not lean. Walk slowly and keep the empty side tight.",
    ),
    exercise(
        "Front Rack Carry",
        "carry_grip",
        "gpp",
        "carry",
        "kettlebells or dumbbells",
        "loaded carry",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        20,
        45,
        7.5,
        "Upper-back, trunk, and breathing under load.",
        ["grip", "core", "grappling"],
        distance="20-45 sec",
        session_slot="grip_gpp",
        method_tag="gpp",
        body_region="grip_core",
        substitution_group="loaded_carry",
        modality_group="loaded_carry",
        progression_style="time_or_load_progression",
        fatigue_points=5,
        technical_transfer="high",
        coaching_cues="Keep elbows down, ribs controlled, and breathe behind the brace.",
    ),
    exercise(
        "Dead Hang",
        "carry_grip",
        "gpp",
        "carry",
        "pull-up bar",
        "bodyweight grip",
        "low",
        "high",
        "low",
        "low",
        3,
        20,
        45,
        7.0,
        "Grip endurance and shoulder decompression.",
        ["grip", "shoulders", "grappling"],
        distance="20-45 sec",
        session_slot="grip_gpp",
        method_tag="gpp",
        body_region="grip_shoulders",
        substitution_group="grip_endurance",
        modality_group="bodyweight_grip",
        progression_style="time_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Hang actively enough to protect shoulders, but do not shrug hard.",
    ),
    exercise(
        "Plate Pinch Hold",
        "carry_grip",
        "gpp",
        "carry",
        "plates",
        "grip hold",
        "low",
        "high",
        "low",
        "low",
        3,
        20,
        40,
        7.0,
        "Pinch grip endurance.",
        ["grip", "forearms"],
        distance="20-40 sec",
        session_slot="grip_gpp",
        method_tag="gpp",
        body_region="grip",
        substitution_group="grip_endurance",
        modality_group="grip_hold",
        progression_style="time_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Pinch hard, keep shoulders relaxed, and stop before grip fully fails.",
    ),

    # -------------------------------------------------------------------------
    # Arms / forearms
    # -------------------------------------------------------------------------
    exercise(
        "Hammer Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "dumbbells",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        10,
        15,
        7.5,
        "Arm and grip support.",
        ["grip", "arms", "pump"],
        session_slot="arm_grip_accessory",
        method_tag="repeated_effort",
        body_region="arms_grip",
        substitution_group="arm_accessory",
        modality_group="isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Keep wrists neutral and control the lowering.",
    ),
    exercise(
        "Reverse Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "barbell or dumbbells",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        10,
        15,
        7.0,
        "Brachialis and forearm strength.",
        ["grip", "arms", "forearms"],
        session_slot="arm_grip_accessory",
        method_tag="repeated_effort",
        body_region="forearms",
        substitution_group="forearm_accessory",
        modality_group="isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Keep elbows quiet and avoid swinging.",
    ),
    exercise(
        "Reverse Wrist Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "dumbbell or barbell",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        12,
        20,
        7.0,
        "Forearm balance.",
        ["grip", "forearms"],
        session_slot="arm_grip_accessory",
        method_tag="repeated_effort",
        body_region="forearms",
        substitution_group="forearm_accessory",
        modality_group="isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Use controlled range and avoid rushing.",
    ),
    exercise(
        "Wrist Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "dumbbell or barbell",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        12,
        20,
        7.0,
        "Forearm support.",
        ["grip", "forearms"],
        session_slot="arm_grip_accessory",
        method_tag="repeated_effort",
        body_region="forearms",
        substitution_group="forearm_accessory",
        modality_group="isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Squeeze at the top and control the descent.",
    ),
    exercise(
        "Triceps Pressdown",
        "arm_accessory",
        "accessory",
        "strength",
        "cable",
        "isolation",
        "low",
        "low",
        "low",
        "low",
        3,
        10,
        15,
        7.0,
        "Triceps accessory volume.",
        ["arms", "pump"],
        session_slot="arm_accessory",
        method_tag="repeated_effort",
        body_region="arms",
        substitution_group="arm_accessory",
        modality_group="cable_isolation",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="low",
        coaching_cues="Pin elbows and finish with a hard lockout.",
    ),

    # -------------------------------------------------------------------------
    # Core / trunk
    # -------------------------------------------------------------------------
    exercise(
        "GHR Sit-Up",
        "core",
        "accessory",
        "bodyweight",
        "GHR bench",
        "bodyweight",
        "medium",
        "medium",
        "medium",
        "medium",
        2,
        8,
        12,
        7.0,
        "Core strength.",
        ["core", "trunk"],
        session_slot="trunk_strength",
        method_tag="repeated_effort",
        body_region="core",
        substitution_group="core_flexion",
        modality_group="bodyweight_core",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Control the range and avoid yanking through the hip flexors.",
    ),
    exercise(
        "Hanging Knee Raise",
        "core",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "medium",
        "medium",
        "low",
        2,
        8,
        12,
        7.0,
        "Abs and hip flexor control.",
        ["core", "grip"],
        session_slot="trunk_strength",
        method_tag="repeated_effort",
        body_region="core_grip",
        substitution_group="core_flexion",
        modality_group="bodyweight_core",
        progression_style="rep_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Control swing and lift pelvis slightly at the top.",
    ),
    exercise(
        "Ab Wheel",
        "core",
        "accessory",
        "bodyweight",
        "ab wheel",
        "bodyweight",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        6,
        12,
        7.5,
        "Anti-extension core strength.",
        ["core", "brace"],
        session_slot="trunk_strength",
        method_tag="repeated_effort",
        body_region="core",
        substitution_group="anti_extension_core",
        modality_group="bodyweight_core",
        progression_style="rep_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Keep ribs down and only roll as far as you can control.",
    ),
    exercise(
        "Pallof Press",
        "core",
        "accessory",
        "strength",
        "cable or band",
        "anti-rotation",
        "low",
        "high",
        "low",
        "low",
        3,
        8,
        12,
        6.5,
        "Anti-rotation trunk work.",
        ["core", "grappling"],
        session_slot="core_anti_rotation",
        method_tag="repeated_effort",
        body_region="core",
        substitution_group="anti_rotation_core",
        modality_group="cable_core",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Press straight out, resist rotation, and breathe behind the brace.",
    ),
    exercise(
        "Side Plank",
        "core",
        "accessory",
        "mobility",
        "floor",
        "isometric",
        "low",
        "medium",
        "low",
        "low",
        2,
        20,
        45,
        6.0,
        "Lateral trunk endurance.",
        ["core", "brace"],
        hold_seconds=30,
        side="each side",
        intensity_target="strong brace",
        session_slot="core_anti_lateral_flexion",
        method_tag="yielding_isometric",
        body_region="core",
        substitution_group="anti_lateral_core",
        modality_group="bodyweight_core",
        progression_style="time_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Keep hips high and ribs stacked.",
    ),
    exercise(
        "Plank",
        "core",
        "accessory",
        "mobility",
        "floor",
        "isometric",
        "low",
        "medium",
        "low",
        "low",
        2,
        30,
        60,
        7.0,
        "Trunk stiffness. Time is in seconds.",
        ["core", "brace"],
        hold_seconds=45,
        intensity_target="strong brace",
        session_slot="trunk_strength",
        method_tag="yielding_isometric",
        body_region="core",
        substitution_group="anti_extension_core",
        modality_group="bodyweight_core",
        progression_style="time_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Squeeze glutes, exhale ribs down, and stay long through the crown of the head.",
    ),
    exercise(
        "Dead Bug",
        "core",
        "recovery_accessory",
        "mobility",
        "floor",
        "bodyweight",
        "low",
        "medium",
        "low",
        "low",
        2,
        8,
        12,
        5.0,
        "Breathing and bracing.",
        ["core", "recovery"],
        intensity_target="controlled breathing",
        session_slot="core_breathing",
        method_tag="recovery",
        body_region="core",
        substitution_group="core_breathing",
        modality_group="bodyweight_core",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Exhale fully, keep low back quiet, and move slowly.",
    ),
    exercise(
        "Bear Crawl",
        "core",
        "gpp",
        "conditioning",
        "floor",
        "locomotion",
        "medium",
        "high",
        "medium",
        "low",
        3,
        20,
        40,
        7.0,
        "Trunk, shoulders, and coordination.",
        ["core", "gpp", "grappling"],
        distance="20-40 sec",
        session_slot="grappling_gpp",
        method_tag="gpp",
        body_region="full_body",
        substitution_group="locomotion_gpp",
        modality_group="locomotion",
        progression_style="density_progression",
        fatigue_points=4,
        technical_transfer="high",
        coaching_cues="Move quietly, keep hips low, and maintain opposite arm/leg rhythm.",
    ),

    # -------------------------------------------------------------------------
    # Neck
    # -------------------------------------------------------------------------
    exercise(
        "Neck Isometrics",
        "neck",
        "recovery_accessory",
        "mobility",
        "bodyweight or hands",
        "isometric",
        "low",
        "high",
        "low",
        "low",
        2,
        10,
        20,
        5.0,
        "Controlled neck work. Do not strain.",
        ["neck", "grappling"],
        intensity_target="easy controlled pressure",
        session_slot="neck_prep",
        method_tag="yielding_isometric",
        body_region="neck",
        substitution_group="neck_isometric",
        modality_group="bodyweight_isometric",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="high",
        coaching_cues="Use gentle pressure in multiple directions. No pain, no grinding.",
    ),
    exercise(
        "Quadruped Neck CARs",
        "neck",
        "recovery_accessory",
        "mobility",
        "bodyweight",
        "CARs",
        "low",
        "high",
        "low",
        "low",
        1,
        2,
        3,
        3.0,
        "Slow controlled neck circles in a quadruped position.",
        ["neck", "mobility", "CARs", "grappling"],
        session_slot="neck_prep",
        method_tag="mobility_control",
        body_region="neck",
        mobility_style="CARs",
        substitution_group="neck_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="high",
        coaching_cues="Move slowly through pain-free range and avoid compensating through the shoulders.",
    ),
    exercise(
        "Banded Neck Extension",
        "neck",
        "accessory",
        "strength",
        "band",
        "isolation",
        "low",
        "high",
        "low",
        "low",
        2,
        12,
        20,
        6.0,
        "Light neck extension strength.",
        ["neck", "grappling"],
        session_slot="neck_strength",
        method_tag="repeated_effort",
        body_region="neck",
        substitution_group="neck_strength",
        modality_group="band_strength",
        progression_style="rep_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Move slowly and keep the jaw relaxed.",
    ),

    # -------------------------------------------------------------------------
    # FRC-inspired mobility / CARs / PAILs-RAILs
    # -------------------------------------------------------------------------
    exercise(
        "Hip CARs",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "CARs",
        "low",
        "high",
        "low",
        "low",
        1,
        2,
        3,
        3.0,
        "Controlled hip circles. Own the range without twisting the trunk.",
        ["mobility", "hips", "CARs", "grappling"],
        side="each side",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="CARs",
        substitution_group="hip_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="high",
        coaching_cues="Move slowly and keep pelvis as still as possible.",
    ),
    exercise(
        "Shoulder CARs",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "CARs",
        "low",
        "medium",
        "low",
        "low",
        1,
        2,
        3,
        3.0,
        "Controlled shoulder circles. Explore pain-free range with no rib flare.",
        ["mobility", "shoulders", "CARs"],
        side="each side",
        session_slot="shoulder_controlled_mobility",
        method_tag="mobility_control",
        body_region="shoulders",
        mobility_style="CARs",
        substitution_group="shoulder_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Keep ribs down and rotate slowly through the shoulder, not the low back.",
    ),
    exercise(
        "Scap CARs",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "CARs",
        "low",
        "medium",
        "low",
        "low",
        2,
        5,
        8,
        3.5,
        "Shoulder blade control through elevation, protraction, depression, and retraction.",
        ["shoulders", "mobility", "upper_back", "CARs"],
        session_slot="shoulder_controlled_mobility",
        method_tag="mobility_control",
        body_region="shoulders",
        mobility_style="CARs",
        substitution_group="shoulder_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Move the shoulder blades without bending elbows or flaring ribs.",
    ),
    exercise(
        "Ankle CARs",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "CARs",
        "low",
        "medium",
        "low",
        "low",
        1,
        3,
        5,
        3.0,
        "Slow ankle circles for joint control.",
        ["mobility", "ankles", "CARs"],
        side="each side",
        session_slot="ankle_controlled_mobility",
        method_tag="mobility_control",
        body_region="ankles",
        mobility_style="CARs",
        substitution_group="ankle_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Move only the ankle while keeping the shin quiet.",
    ),
    exercise(
        "T-Spine CARs",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "CARs",
        "low",
        "high",
        "low",
        "low",
        1,
        3,
        5,
        3.5,
        "Controlled thoracic circles for rotation, flexion, extension, and side bending.",
        ["mobility", "upper_back", "t_spine", "CARs"],
        session_slot="t_spine_mobility",
        method_tag="mobility_control",
        body_region="t_spine",
        mobility_style="CARs",
        substitution_group="t_spine_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="high",
        coaching_cues="Move through the upper back while limiting low-back compensation.",
    ),
    exercise(
        "90/90 Hip PAILs/RAILs",
        "mobility",
        "mobility",
        "mobility",
        "floor",
        "PAILs/RAILs",
        "low",
        "high",
        "medium",
        "low",
        2,
        30,
        60,
        5.0,
        "Use 90/90 position, then progressive isometric effort into and out of the end range.",
        ["mobility", "hips", "PAILs", "RAILs", "grappling"],
        hold_seconds=45,
        side="each side",
        intensity_target="progressive end-range tension",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="PAILs/RAILs",
        substitution_group="hip_mobility",
        modality_group="end_range_isometric",
        progression_style="control_progression",
        fatigue_points=3,
        technical_transfer="high",
        coaching_cues="Start easy, ramp tension gradually, and never force pain.",
    ),
    exercise(
        "Half-Kneeling Hip Flexor PAILs/RAILs",
        "mobility",
        "mobility",
        "mobility",
        "floor",
        "PAILs/RAILs",
        "low",
        "medium",
        "medium",
        "low",
        2,
        30,
        60,
        5.0,
        "Hip flexor end-range isometric work from a half-kneeling position.",
        ["mobility", "hips", "PAILs", "RAILs"],
        hold_seconds=45,
        side="each side",
        intensity_target="progressive end-range tension",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="PAILs/RAILs",
        substitution_group="hip_mobility",
        modality_group="end_range_isometric",
        progression_style="control_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Squeeze glute on the down knee and ramp tension slowly.",
    ),
    exercise(
        "Pigeon PAILs/RAILs",
        "mobility",
        "mobility",
        "mobility",
        "floor",
        "PAILs/RAILs",
        "low",
        "medium",
        "medium",
        "low",
        2,
        30,
        60,
        5.0,
        "Hip external rotation end-range isometric work.",
        ["mobility", "hips", "PAILs", "RAILs"],
        hold_seconds=45,
        side="each side",
        intensity_target="progressive end-range tension",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="PAILs/RAILs",
        substitution_group="hip_mobility",
        modality_group="end_range_isometric",
        progression_style="control_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Keep tension controlled and do not crank the knee.",
    ),
    exercise(
        "Lat PAILs/RAILs",
        "stretch",
        "stretch",
        "mobility",
        "bench, rack, or band",
        "PAILs/RAILs",
        "low",
        "medium",
        "medium",
        "low",
        2,
        30,
        60,
        5.0,
        "End-range lat tension and active pull into new range.",
        ["shoulders", "lats", "PAILs", "RAILs", "stretch"],
        hold_seconds=45,
        side="each side",
        intensity_target="progressive end-range tension",
        session_slot="upper_body_mobility",
        method_tag="mobility_control",
        body_region="lats",
        mobility_style="PAILs/RAILs",
        substitution_group="upper_body_mobility",
        modality_group="end_range_isometric",
        progression_style="control_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Keep ribs down and ramp effort without shoulder pain.",
    ),
    exercise(
        "Shoulder Internal Rotation PAILs/RAILs",
        "stretch",
        "stretch",
        "mobility",
        "band or wall",
        "PAILs/RAILs",
        "low",
        "medium",
        "medium",
        "low",
        2,
        30,
        60,
        5.0,
        "Controlled shoulder internal rotation end-range work.",
        ["shoulders", "PAILs", "RAILs", "stretch"],
        hold_seconds=45,
        side="each side",
        intensity_target="progressive end-range tension",
        session_slot="shoulder_controlled_mobility",
        method_tag="mobility_control",
        body_region="shoulders",
        mobility_style="PAILs/RAILs",
        substitution_group="shoulder_mobility",
        modality_group="end_range_isometric",
        progression_style="control_progression",
        fatigue_points=3,
        technical_transfer="medium",
        coaching_cues="Keep intensity modest and avoid anterior shoulder irritation.",
    ),

    # -------------------------------------------------------------------------
    # Specific mobility circuits / movement prep
    # -------------------------------------------------------------------------
    exercise(
        "BJJ Hip & T-Spine Mobility Circuit",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "mobility circuit",
        "low",
        "high",
        "low",
        "low",
        1,
        8,
        12,
        3.0,
        "Move through 90/90 switches, adductor rockbacks, thoracic rotations, and deep squat breathing. Keep it controlled and useful for grappling positions.",
        ["mobility", "recovery", "hips", "upper_back", "grappling"],
        duration_minutes=10,
        intensity_target="smooth controlled range",
        session_slot="movement_prep",
        method_tag="movement_prep",
        body_region="hips_t_spine",
        mobility_style="mobility_circuit",
        substitution_group="movement_prep",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Move like prep for grappling positions, not random stretching.",
    ),
    exercise(
        "Grappler Hip Reset",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "mobility circuit",
        "low",
        "high",
        "low",
        "low",
        2,
        5,
        8,
        3.5,
        "Cycle through shin box switches, hip airplanes, and half-kneeling hip flexor pulses. Focus on usable hip range for guard, passing, and scrambling.",
        ["mobility", "hips", "grappling", "recovery"],
        duration_minutes=8,
        intensity_target="controlled range",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="mobility_circuit",
        substitution_group="hip_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Own each position and avoid rushing.",
    ),
    exercise(
        "Shoulder CARs + Scap Push-Up Circuit",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "mobility circuit",
        "low",
        "medium",
        "low",
        "low",
        2,
        5,
        8,
        3.5,
        "Controlled shoulder circles followed by scap push-ups. Use this to restore shoulder control after pressing, posting, and framing.",
        ["mobility", "shoulders", "upper_back", "recovery"],
        duration_minutes=6,
        intensity_target="slow controlled reps",
        session_slot="shoulder_controlled_mobility",
        method_tag="mobility_control",
        body_region="shoulders",
        mobility_style="mobility_circuit",
        substitution_group="shoulder_mobility",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Keep the rib cage quiet while the shoulder blades move.",
    ),
    exercise(
        "Combat Base Mobility Circuit",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "mobility circuit",
        "low",
        "high",
        "low",
        "low",
        2,
        4,
        6,
        4.0,
        "Move between combat base, low lunge, hamstring reach, and thoracic rotation. Treat it like positional mobility, not random stretching.",
        ["mobility", "hips", "grappling", "recovery"],
        duration_minutes=8,
        intensity_target="smooth positional control",
        session_slot="movement_prep",
        method_tag="movement_prep",
        body_region="hips_t_spine",
        mobility_style="mobility_circuit",
        substitution_group="movement_prep",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Move with balance and posture like you are preparing to wrestle or pass.",
    ),
    exercise(
        "Deep Squat Breathing",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "positional breathing",
        "low",
        "medium",
        "low",
        "low",
        2,
        30,
        60,
        3.0,
        "Sit in a comfortable deep squat, breathe slowly, and shift gently side to side. Do not force depth.",
        ["mobility", "hips", "ankles", "recovery"],
        hold_seconds=45,
        intensity_target="relaxed breathing",
        session_slot="positional_breathing",
        method_tag="recovery",
        body_region="hips_ankles",
        mobility_style="positional_breathing",
        substitution_group="breathing_mobility",
        modality_group="bodyweight_mobility",
        progression_style="breathing_control",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Relax into the position and breathe through the ribs and back.",
    ),
    exercise(
        "Open Guard Hip Series",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "ground mobility",
        "low",
        "high",
        "low",
        "low",
        2,
        6,
        10,
        4.0,
        "Use seated hip switches, technical stand-up patterning, and supine hip rotations. Keep the movement smooth and BJJ-specific.",
        ["mobility", "hips", "grappling", "recovery"],
        duration_minutes=8,
        intensity_target="smooth controlled movement",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="ground_mobility",
        substitution_group="hip_mobility",
        modality_group="ground_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Treat each rep like controlled grappling movement.",
    ),
    exercise(
        "World's Greatest Stretch",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "flow",
        "low",
        "medium",
        "low",
        "low",
        2,
        4,
        6,
        4.0,
        "Full-body hip, t-spine, and hamstring mobility.",
        ["mobility", "hips"],
        side="each side",
        intensity_target="smooth controlled range",
        session_slot="movement_prep",
        method_tag="movement_prep",
        body_region="full_body",
        mobility_style="dynamic_mobility",
        substitution_group="movement_prep",
        modality_group="bodyweight_mobility",
        progression_style="control_progression",
        fatigue_points=2,
        technical_transfer="medium",
        coaching_cues="Move slowly and breathe into the rotation.",
    ),
    exercise(
        "90/90 Hip Switch",
        "mobility",
        "mobility",
        "mobility",
        "floor",
        "mobility",
        "low",
        "medium",
        "low",
        "low",
        2,
        6,
        10,
        4.0,
        "Hip rotation control.",
        ["hips", "mobility"],
        intensity_target="controlled range",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="hips",
        mobility_style="dynamic_mobility",
        substitution_group="hip_mobility",
        modality_group="ground_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Keep the motion controlled and avoid dumping into the low back.",
    ),
    exercise(
        "Adductor Rockback",
        "mobility",
        "mobility",
        "mobility",
        "floor",
        "mobility",
        "low",
        "high",
        "low",
        "low",
        2,
        8,
        12,
        4.0,
        "Adductor mobility for grappling positions.",
        ["hips", "mobility", "grappling"],
        side="each side",
        session_slot="hip_controlled_mobility",
        method_tag="mobility_control",
        body_region="adductors",
        mobility_style="dynamic_mobility",
        substitution_group="hip_mobility",
        modality_group="ground_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="high",
        coaching_cues="Rock back slowly and keep the spine long.",
    ),
    exercise(
        "Thoracic Rotation",
        "mobility",
        "mobility",
        "mobility",
        "floor",
        "mobility",
        "low",
        "medium",
        "low",
        "low",
        2,
        6,
        10,
        3.5,
        "T-spine rotation and breathing.",
        ["mobility", "upper_back", "t_spine"],
        side="each side",
        session_slot="t_spine_mobility",
        method_tag="mobility_control",
        body_region="t_spine",
        mobility_style="dynamic_mobility",
        substitution_group="t_spine_mobility",
        modality_group="ground_mobility",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="high",
        coaching_cues="Rotate through the upper back and exhale into the end range.",
    ),

    # -------------------------------------------------------------------------
    # Static stretching / upper-body mobility finishers
    # -------------------------------------------------------------------------
    exercise(
        "Couch Stretch",
        "stretch",
        "stretch",
        "stretch",
        "bench or wall",
        "static stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        45,
        60,
        3.0,
        "Open hips and quads. Keep breathing relaxed.",
        ["hips", "stretch"],
        hold_seconds=60,
        side="each side",
        intensity_target="easy-moderate",
        session_slot="static_hip_stretch",
        method_tag="recovery",
        body_region="hips_quads",
        mobility_style="static_stretch",
        substitution_group="hip_stretch",
        modality_group="static_stretch",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Squeeze glute lightly and avoid arching the low back.",
    ),
    exercise(
        "Lat Stretch",
        "stretch",
        "stretch",
        "stretch",
        "bench or rack",
        "static stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        30,
        45,
        3.0,
        "Open lats and shoulders after pulling.",
        ["shoulders", "stretch"],
        hold_seconds=45,
        side="each side",
        intensity_target="easy",
        session_slot="upper_body_mobility",
        method_tag="recovery",
        body_region="lats",
        mobility_style="static_stretch",
        substitution_group="upper_body_mobility",
        modality_group="static_stretch",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Breathe into the side ribs and do not crank the shoulder.",
    ),
    exercise(
        "Pigeon Stretch",
        "stretch",
        "stretch",
        "stretch",
        "floor",
        "static stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        45,
        60,
        3.0,
        "Hip external rotation stretch.",
        ["hips", "stretch"],
        hold_seconds=60,
        side="each side",
        intensity_target="easy-moderate",
        session_slot="static_hip_stretch",
        method_tag="recovery",
        body_region="hips",
        mobility_style="static_stretch",
        substitution_group="hip_stretch",
        modality_group="static_stretch",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Keep the knee comfortable and breathe slowly.",
    ),
    exercise(
        "Hamstring Floss",
        "stretch",
        "stretch",
        "mobility",
        "floor or band",
        "dynamic stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        8,
        12,
        3.0,
        "Dynamic hamstring mobility.",
        ["hamstrings", "stretch"],
        side="each side",
        intensity_target="easy",
        session_slot="posterior_chain_mobility",
        method_tag="recovery",
        body_region="hamstrings",
        mobility_style="dynamic_stretch",
        substitution_group="posterior_chain_mobility",
        modality_group="dynamic_stretch",
        progression_style="control_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Move gently and avoid nerve-like symptoms.",
    ),
    exercise(
        "Pec Doorway Stretch",
        "stretch",
        "stretch",
        "stretch",
        "doorway",
        "static stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        30,
        45,
        3.0,
        "Open chest and anterior shoulder.",
        ["shoulders", "stretch"],
        hold_seconds=45,
        side="each side",
        intensity_target="easy",
        session_slot="upper_body_mobility",
        method_tag="recovery",
        body_region="pecs_shoulders",
        mobility_style="static_stretch",
        substitution_group="upper_body_mobility",
        modality_group="static_stretch",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Keep shoulder down and breathe slowly.",
    ),
    exercise(
        "Foam Roll T-Spine",
        "mobility",
        "mobility",
        "mobility",
        "foam roller",
        "soft tissue",
        "low",
        "medium",
        "low",
        "low",
        1,
        60,
        120,
        2.0,
        "Roll the length of the ribcage and gently flex/extend through the upper back.",
        ["upper_back", "t_spine", "mobility", "recovery"],
        duration_minutes=2,
        intensity_target="easy",
        session_slot="upper_body_mobility",
        method_tag="recovery",
        body_region="t_spine",
        mobility_style="soft_tissue",
        substitution_group="upper_body_mobility",
        modality_group="foam_roll",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Stay on the ribcage area and avoid cranking the neck.",
    ),
    exercise(
        "Foam Roll Lats",
        "mobility",
        "mobility",
        "mobility",
        "foam roller",
        "soft tissue",
        "low",
        "medium",
        "low",
        "low",
        1,
        60,
        120,
        2.0,
        "Roll from mid-ribcage toward the armpit and pause on tension.",
        ["lats", "shoulders", "mobility", "recovery"],
        duration_minutes=2,
        side="each side",
        intensity_target="easy",
        session_slot="upper_body_mobility",
        method_tag="recovery",
        body_region="lats",
        mobility_style="soft_tissue",
        substitution_group="upper_body_mobility",
        modality_group="foam_roll",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Pause where tight but keep breathing relaxed.",
    ),
    exercise(
        "Foam Roll Pec/Shoulder",
        "mobility",
        "mobility",
        "mobility",
        "foam roller or ball",
        "soft tissue",
        "low",
        "medium",
        "low",
        "low",
        1,
        60,
        120,
        2.0,
        "Roll pec/shoulder area and sweep arm to capture tension.",
        ["pecs", "shoulders", "mobility", "recovery"],
        duration_minutes=2,
        side="each side",
        intensity_target="easy",
        session_slot="upper_body_mobility",
        method_tag="recovery",
        body_region="pecs_shoulders",
        mobility_style="soft_tissue",
        substitution_group="upper_body_mobility",
        modality_group="foam_roll",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Use mild pressure and do not irritate the front of the shoulder.",
    ),
    exercise(
        "Band-Assisted Lat Stretch",
        "stretch",
        "stretch",
        "stretch",
        "band",
        "band-assisted stretch",
        "low",
        "medium",
        "low",
        "low",
        1,
        60,
        120,
        3.0,
        "Band-assisted lat stretch. Move farther from the anchor to increase stretch.",
        ["lats", "shoulders", "stretch"],
        hold_seconds=90,
        side="each side",
        intensity_target="easy-moderate",
        session_slot="upper_body_mobility",
        method_tag="recovery",
        body_region="lats",
        mobility_style="band_assisted_stretch",
        substitution_group="upper_body_mobility",
        modality_group="band_stretch",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Keep ribs down and breathe into the side body.",
    ),
    exercise(
        "Band-Assisted Shoulder Internal Rotation Stretch",
        "stretch",
        "stretch",
        "stretch",
        "band",
        "band-assisted stretch",
        "low",
        "medium",
        "low",
        "low",
        1,
        60,
        120,
        3.0,
        "Band-assisted shoulder internal rotation stretch.",
        ["shoulders", "stretch"],
        hold_seconds=90,
        side="each side",
        intensity_target="easy-moderate",
        session_slot="shoulder_controlled_mobility",
        method_tag="recovery",
        body_region="shoulders",
        mobility_style="band_assisted_stretch",
        substitution_group="shoulder_mobility",
        modality_group="band_stretch",
        progression_style="time_progression",
        fatigue_points=1,
        technical_transfer="medium",
        coaching_cues="Keep it gentle and avoid pinching in the front of the shoulder.",
    ),

    # -------------------------------------------------------------------------
    # Combat-skill cardio / technical conditioning
    # -------------------------------------------------------------------------
    exercise(
        "Light Shadow Boxing",
        "conditioning",
        "cardio",
        "cardio_skill",
        "open space",
        "technical cardio",
        "low",
        "high",
        "low",
        "low",
        4,
        2,
        3,
        5.0,
        "Light technical rounds. Work stance, rhythm, defense, and clean punches without turning it into hard conditioning.",
        ["cardio", "technical", "boxing", "combat"],
        duration_minutes=10,
        heart_rate_target="Zone 2-3 or conversational pace",
        intensity_target="RPE 4-5",
        session_slot="technical_cardio",
        method_tag="skill_conditioning",
        body_region="full_body",
        substitution_group="technical_cardio",
        modality_group="shadow_boxing",
        progression_style="duration_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Stay loose, keep guard honest, and prioritize clean mechanics over speed.",
    ),
    exercise(
        "Muay Thai Footwork Rounds",
        "conditioning",
        "cardio",
        "cardio_skill",
        "open space",
        "technical cardio",
        "low",
        "high",
        "low",
        "low",
        4,
        2,
        3,
        5.0,
        "Light footwork rounds. Work step-outs, pivots, stance recovery, checks, and teep positioning.",
        ["cardio", "technical", "muay_thai", "footwork", "combat"],
        duration_minutes=10,
        heart_rate_target="Zone 2-3 or nasal breathing when possible",
        intensity_target="RPE 4-5",
        session_slot="technical_cardio",
        method_tag="skill_conditioning",
        body_region="full_body",
        substitution_group="technical_cardio",
        modality_group="muay_thai_footwork",
        progression_style="duration_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Stay balanced after every step and reset your stance every rep.",
    ),
    exercise(
        "Jump Rope Footwork",
        "conditioning",
        "cardio",
        "conditioning",
        "jump rope",
        "footwork cardio",
        "medium",
        "high",
        "medium",
        "medium",
        5,
        60,
        120,
        6.0,
        "Footwork and rhythm conditioning. Keep it smooth, not frantic.",
        ["cardio", "footwork", "combat"],
        duration_minutes=10,
        heart_rate_target="Zone 2-3",
        intensity_target="smooth rhythm",
        session_slot="technical_cardio",
        method_tag="skill_conditioning",
        body_region="full_body",
        substitution_group="technical_cardio",
        modality_group="jump_rope",
        progression_style="duration_progression",
        fatigue_points=3,
        technical_transfer="high",
        coaching_cues="Relax the shoulders, bounce lightly, and keep breathing steady.",
    ),
    exercise(
        "Boxing Step-and-Pivot Rounds",
        "conditioning",
        "cardio",
        "cardio_skill",
        "open space",
        "technical cardio",
        "low",
        "high",
        "low",
        "low",
        4,
        2,
        3,
        5.0,
        "Move through step-jab, pivot, angle exit, and stance reset patterns.",
        ["cardio", "technical", "boxing", "footwork"],
        duration_minutes=10,
        heart_rate_target="Zone 2-3",
        intensity_target="RPE 4-5",
        session_slot="technical_cardio",
        method_tag="skill_conditioning",
        body_region="full_body",
        substitution_group="technical_cardio",
        modality_group="boxing_footwork",
        progression_style="duration_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Finish every combination in stance and avoid crossing feet.",
    ),
    exercise(
        "Defensive Movement Rounds",
        "conditioning",
        "cardio",
        "cardio_skill",
        "open space",
        "technical cardio",
        "low",
        "high",
        "low",
        "low",
        3,
        2,
        3,
        5.0,
        "Light defensive movement: slips, rolls, frames, stance resets, and exits.",
        ["cardio", "technical", "defense", "combat"],
        duration_minutes=8,
        heart_rate_target="Zone 2-3",
        intensity_target="RPE 4-5",
        session_slot="technical_cardio",
        method_tag="skill_conditioning",
        body_region="full_body",
        substitution_group="technical_cardio",
        modality_group="defensive_movement",
        progression_style="duration_progression",
        fatigue_points=2,
        technical_transfer="high",
        coaching_cues="Move smoothly and stay balanced enough to counter.",
    ),
    exercise(
        "Bag-Free Technical Flow",
        "conditioning",
        "cardio",
        "cardio_skill",
        "open space",
        "technical cardio",
        "low",
        "high",
        "low",
        "low",
        3,
        3,
        5,
        5.0,
        "Blend light shadow boxing, sprawls without impact, stance switches, and footwork. Keep it technical.",
        ["cardio", "technical", "combat", "flow"],
        duration_minutes=12,
        heart_rate_target="Zone 2-3",
        intensity_target="RPE 4-5",
        session_slot="technical_cardio",
        method_tag="skill_conditioning",
        body_region="full_body",
        substitution_group="technical_cardio",
        modality_group="technical_flow",
        progression_style="duration_progression",
        fatigue_points=3,
        technical_transfer="high",
        coaching_cues="Never rush. Prioritize posture, stance, and breathing.",
    ),
    exercise(
        "Incline Walk",
        "conditioning",
        "cardio",
        "cardio",
        "treadmill",
        "cyclical cardio",
        "low",
        "medium",
        "low",
        "low",
        1,
        10,
        20,
        4.0,
        "Easy pace. Nasal breathing if possible.",
        ["cardio", "recovery"],
        duration_minutes=15,
        heart_rate_target="Zone 2 or nasal breathing",
        intensity_target="easy",
        session_slot="zone2_cardio",
        method_tag="recovery",
        body_region="full_body",
        substitution_group="zone2_cardio",
        modality_group="cyclical_cardio",
        progression_style="duration_progression",
        fatigue_points=2,
        technical_transfer="low",
        coaching_cues="Keep pace easy enough that you could speak in short sentences.",
    ),
    exercise(
        "Bike",
        "conditioning",
        "cardio",
        "cardio",
        "bike",
        "cyclical cardio",
        "low",
        "medium",
        "low",
        "low",
        1,
        8,
        12,
        5.0,
        "Easy conditioning. Keep it smooth.",
        ["cardio", "recovery"],
        duration_minutes=10,
        heart_rate_target="Zone 2 or nasal breathing",
        intensity_target="easy-moderate",
        session_slot="zone2_cardio",
        method_tag="recovery",
        body_region="full_body",
        substitution_group="zone2_cardio",
        modality_group="cyclical_cardio",
        progression_style="duration_progression",
        fatigue_points=2,
        technical_transfer="low",
        coaching_cues="Smooth cadence and easy breathing.",
    ),
    exercise(
        "Row Erg",
        "conditioning",
        "cardio",
        "cardio",
        "rower",
        "cyclical cardio",
        "medium",
        "medium",
        "medium",
        "low",
        1,
        6,
        10,
        6.0,
        "Moderate conditioning. Avoid turning it into a death set.",
        ["cardio", "conditioning"],
        duration_minutes=8,
        heart_rate_target="Zone 2-3",
        intensity_target="moderate",
        session_slot="zone2_cardio",
        method_tag="gpp",
        body_region="full_body",
        substitution_group="zone2_cardio",
        modality_group="cyclical_cardio",
        progression_style="duration_progression",
        fatigue_points=4,
        technical_transfer="medium",
        coaching_cues="Drive legs, swing hips, pull arms. Reverse the order on recovery.",
    ),
    exercise(
        "Assault Bike Intervals",
        "conditioning",
        "cardio",
        "conditioning",
        "assault bike",
        "intervals",
        "medium",
        "high",
        "medium",
        "low",
        6,
        20,
        40,
        7.0,
        "Short intervals. Hard but not reckless.",
        ["cardio", "conditioning", "combat"],
        heart_rate_target="Hard intervals, full recovery",
        intensity_target="RPE 7",
        session_slot="gpp_conditioning",
        method_tag="gpp",
        body_region="full_body",
        substitution_group="conditioning",
        modality_group="intervals",
        progression_style="density_progression",
        fatigue_points=6,
        technical_transfer="medium",
        coaching_cues="Hard effort, full recovery, and stop before output collapses.",
    ),
    exercise(
        "Sled Push",
        "conditioning",
        "gpp",
        "conditioning",
        "sled",
        "loaded conditioning",
        "medium",
        "high",
        "medium",
        "low",
        6,
        15,
        30,
        7.0,
        "Leg drive and conditioning with low eccentric damage.",
        ["conditioning", "lower", "gpp"],
        distance="15-30 yd",
        session_slot="gpp_conditioning",
        method_tag="gpp",
        body_region="lower_full_body",
        substitution_group="conditioning",
        modality_group="sled",
        progression_style="distance_or_load_progression",
        fatigue_points=5,
        technical_transfer="high",
        coaching_cues="Drive through the floor and keep torso angle consistent.",
    ),
]


def get_exercise_catalog() -> list[dict[str, Any]]:
    return [exercise.copy() for exercise in EXERCISE_CATALOG]
