from typing import Any


def exercise(
    name: str,
    movement_pattern: str,
    exercise_category: str,
    prescription_type: str,
    equipment: str,
    modality: str,
    fatigue_cost: str,
    combat_transfer: str,
    difficulty: str,
    joint_stress: str,
    default_sets: int,
    reps_min: int,
    reps_max: int,
    target_rpe: float,
    notes: str,
    tags: list[str] | None = None,
    duration_minutes: int | None = None,
    hold_seconds: int | None = None,
    distance: str = "",
    heart_rate_target: str = "",
    intensity_target: str = "",
    side: str = "",
) -> dict[str, Any]:
    return {
        "exercise_name": name,
        "movement_pattern": movement_pattern,
        "exercise_category": exercise_category,
        "prescription_type": prescription_type,
        "equipment": equipment,
        "modality": modality,
        "fatigue_cost": fatigue_cost,
        "combat_transfer": combat_transfer,
        "difficulty": difficulty,
        "joint_stress": joint_stress,
        "planned_sets": default_sets,
        "planned_reps_min": reps_min,
        "planned_reps_max": reps_max,
        "planned_weight": 0,
        "target_rpe": target_rpe,
        "notes": notes,
        "tags": tags or [],
        "duration_minutes": duration_minutes,
        "hold_seconds": hold_seconds,
        "distance": distance,
        "heart_rate_target": heart_rate_target,
        "intensity_target": intensity_target,
        "side": side,
    }


EXERCISE_CATALOG = [
    # Main lifts
    exercise(
        "Trap Bar Deadlift",
        "hinge",
        "main_lift",
        "strength",
        "trap bar",
        "free weight",
        "high",
        "high",
        "high",
        "medium",
        3,
        3,
        5,
        8.0,
        "Main hinge strength. Smooth reps only.",
        ["posterior_chain", "grappling", "strength"],
    ),
    exercise(
        "Bench Press",
        "horizontal_push",
        "main_lift",
        "strength",
        "barbell",
        "free weight",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        4,
        6,
        8.0,
        "Main press. Do not grind reps.",
        ["upper", "strength", "press"],
    ),
    exercise(
        "Squat",
        "squat",
        "main_lift",
        "strength",
        "barbell",
        "free weight",
        "high",
        "high",
        "high",
        "high",
        3,
        4,
        6,
        8.0,
        "Main squat pattern. Keep positions clean.",
        ["lower", "strength"],
    ),
    exercise(
        "Weighted Pull-Up",
        "vertical_pull",
        "main_lift",
        "strength",
        "pull-up bar",
        "weighted bodyweight",
        "high",
        "high",
        "high",
        "medium",
        3,
        3,
        6,
        8.0,
        "Added weight only. Prioritize clean reps.",
        ["upper", "grip", "grappling", "pull"],
    ),
    exercise(
        "Weighted Chin-Up",
        "vertical_pull",
        "main_lift",
        "strength",
        "pull-up bar",
        "weighted bodyweight",
        "high",
        "high",
        "high",
        "medium",
        3,
        3,
        6,
        8.0,
        "Added weight only. Chin-up variation for pulling strength.",
        ["upper", "grip", "grappling", "pull"],
    ),

    # Secondary lifts
    exercise(
        "Romanian Deadlift",
        "hinge",
        "secondary_lift",
        "strength",
        "barbell or dumbbells",
        "free weight",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        6,
        10,
        7.5,
        "Hamstrings, glutes, and trunk tension.",
        ["posterior_chain", "grappling"],
    ),
    exercise(
        "Chest-Supported Row",
        "horizontal_pull",
        "secondary_lift",
        "strength",
        "machine or bench + dumbbells",
        "supported pull",
        "medium",
        "high",
        "medium",
        "low",
        3,
        8,
        12,
        8.0,
        "Upper-back strength without taxing the low back.",
        ["upper", "grappling", "posture"],
    ),
    exercise(
        "DB Row",
        "horizontal_pull",
        "accessory",
        "strength",
        "dumbbell",
        "free weight",
        "medium",
        "high",
        "medium",
        "low",
        3,
        8,
        12,
        8.0,
        "Rowing volume for lats and upper back.",
        ["upper", "grappling"],
    ),
    exercise(
        "Landmine Press",
        "vertical_push",
        "secondary_lift",
        "strength",
        "landmine",
        "free weight",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        6,
        10,
        7.5,
        "Athletic pressing without excessive shoulder stress.",
        ["upper", "press", "athletic"],
    ),
    exercise(
        "DB Bench Press",
        "horizontal_push",
        "secondary_lift",
        "strength",
        "dumbbells",
        "free weight",
        "medium",
        "medium",
        "medium",
        "low",
        3,
        8,
        12,
        7.5,
        "Pressing volume with more freedom than barbell bench.",
        ["upper", "press"],
    ),
    exercise(
        "Hack Squat",
        "squat",
        "secondary_lift",
        "strength",
        "machine",
        "machine",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        8,
        12,
        7.5,
        "Squat pattern with more external stability.",
        ["lower", "modality_swap"],
    ),
    exercise(
        "Goblet Squat",
        "squat",
        "accessory",
        "strength",
        "dumbbell or kettlebell",
        "free weight",
        "low",
        "medium",
        "low",
        "low",
        3,
        8,
        12,
        6.5,
        "Light squat pattern. Good for lower-readiness days.",
        ["lower", "light"],
    ),
    exercise(
        "Step-Up",
        "single_leg",
        "accessory",
        "strength",
        "box + dumbbells optional",
        "single-leg",
        "medium",
        "medium",
        "medium",
        "low",
        2,
        8,
        12,
        7.0,
        "Single-leg strength and balance.",
        ["lower", "single_leg"],
    ),
    exercise(
        "Split Squat",
        "single_leg",
        "accessory",
        "strength",
        "dumbbells optional",
        "single-leg",
        "medium",
        "medium",
        "medium",
        "medium",
        3,
        8,
        12,
        7.5,
        "Single-leg strength with trunk control.",
        ["lower", "single_leg"],
    ),
    exercise(
        "Back Extension",
        "posterior_chain",
        "accessory",
        "bodyweight",
        "back extension bench",
        "bodyweight or loaded",
        "medium",
        "high",
        "medium",
        "low",
        3,
        10,
        15,
        7.0,
        "Posterior-chain support and low-back endurance.",
        ["posterior_chain", "grappling"],
    ),

    # Pulling variations
    exercise(
        "Pull-Up",
        "vertical_pull",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        5,
        10,
        8.0,
        "Bodyweight pulling volume.",
        ["upper", "grip", "grappling"],
    ),
    exercise(
        "Chin-Up",
        "vertical_pull",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "high",
        "medium",
        "medium",
        3,
        5,
        10,
        8.0,
        "Bodyweight pulling with more biceps involvement.",
        ["upper", "grip", "grappling"],
    ),
    exercise(
        "Neutral-Grip Pull-Up",
        "vertical_pull",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "high",
        "medium",
        "low",
        3,
        5,
        10,
        7.5,
        "Joint-friendly vertical pull variation.",
        ["upper", "grip", "grappling"],
    ),
    exercise(
        "Lat Pulldown",
        "vertical_pull",
        "accessory",
        "strength",
        "cable machine",
        "machine",
        "low",
        "medium",
        "low",
        "low",
        3,
        8,
        12,
        7.0,
        "Vertical pull substitution when pull-ups are not ideal.",
        ["upper", "modality_swap"],
    ),

    # Carries / grip
    exercise(
        "Farmer Carry",
        "carry_grip",
        "gpp",
        "carry",
        "dumbbells or kettlebells",
        "loaded carry",
        "medium",
        "high",
        "medium",
        "low",
        3,
        30,
        60,
        7.5,
        "Grip, trunk, and posture.",
        ["grip", "gpp", "grappling"],
        distance="30-60 sec",
    ),
    exercise(
        "Suitcase Carry",
        "carry_grip",
        "gpp",
        "carry",
        "dumbbell or kettlebell",
        "loaded carry",
        "medium",
        "high",
        "medium",
        "low",
        3,
        30,
        60,
        7.0,
        "Anti-lateral flexion and grip.",
        ["grip", "core", "gpp"],
        distance="30-60 sec each side",
        side="each side",
    ),
    exercise(
        "Dead Hang",
        "carry_grip",
        "gpp",
        "carry",
        "pull-up bar",
        "bodyweight grip",
        "low",
        "high",
        "low",
        "low",
        3,
        20,
        45,
        7.0,
        "Grip endurance and shoulder decompression.",
        ["grip", "shoulders", "grappling"],
        distance="20-45 sec",
    ),
    exercise(
        "Hammer Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "dumbbells",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        10,
        15,
        7.5,
        "Arm and grip support.",
        ["grip", "arms"],
    ),
    exercise(
        "Reverse Wrist Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "dumbbell or barbell",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        12,
        20,
        7.0,
        "Forearm balance.",
        ["grip", "forearms"],
    ),
    exercise(
        "Wrist Curl",
        "forearm_grip",
        "accessory",
        "strength",
        "dumbbell or barbell",
        "isolation",
        "low",
        "medium",
        "low",
        "low",
        2,
        12,
        20,
        7.0,
        "Forearm support.",
        ["grip", "forearms"],
    ),

    # Core / trunk
    exercise(
        "GHR Sit-Up",
        "core",
        "accessory",
        "bodyweight",
        "GHR bench",
        "bodyweight",
        "medium",
        "medium",
        "medium",
        "medium",
        2,
        8,
        12,
        7.0,
        "Core strength.",
        ["core", "trunk"],
    ),
    exercise(
        "Hanging Knee Raise",
        "core",
        "accessory",
        "bodyweight",
        "pull-up bar",
        "bodyweight",
        "medium",
        "medium",
        "medium",
        "low",
        2,
        8,
        12,
        7.0,
        "Abs and hip flexor control.",
        ["core", "grip"],
    ),
    exercise(
        "Plank",
        "core",
        "accessory",
        "mobility",
        "floor",
        "isometric",
        "low",
        "medium",
        "low",
        "low",
        2,
        30,
        60,
        7.0,
        "Trunk stiffness. Time is in seconds.",
        ["core", "brace"],
        hold_seconds=45,
        intensity_target="strong brace",
    ),
    exercise(
        "Dead Bug",
        "core",
        "recovery_accessory",
        "mobility",
        "floor",
        "bodyweight",
        "low",
        "medium",
        "low",
        "low",
        2,
        8,
        12,
        5.0,
        "Breathing and bracing.",
        ["core", "recovery"],
        intensity_target="controlled breathing",
    ),

    # Neck / mobility / stretch
    exercise(
        "Neck Isometrics",
        "neck",
        "recovery_accessory",
        "mobility",
        "bodyweight or hands",
        "isometric",
        "low",
        "high",
        "low",
        "low",
        2,
        10,
        20,
        5.0,
        "Controlled neck work. Do not strain.",
        ["neck", "grappling"],
        intensity_target="easy controlled pressure",
    ),
    exercise(
        "Hip Airplane",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "mobility",
        "low",
        "medium",
        "medium",
        "low",
        2,
        5,
        8,
        4.0,
        "Hip control and balance.",
        ["hips", "mobility"],
        side="each side",
        intensity_target="controlled range",
    ),
    exercise(
        "Mobility Flow",
        "mobility",
        "mobility",
        "mobility",
        "bodyweight",
        "flow",
        "low",
        "medium",
        "low",
        "low",
        1,
        5,
        10,
        3.0,
        "Move smoothly. Do not force range.",
        ["mobility", "recovery"],
        duration_minutes=8,
        intensity_target="smooth and controlled",
    ),
    exercise(
        "Couch Stretch",
        "stretch",
        "stretch",
        "stretch",
        "bench or wall",
        "static stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        45,
        60,
        3.0,
        "Open hips and quads. Keep breathing relaxed.",
        ["hips", "stretch"],
        hold_seconds=60,
        side="each side",
        intensity_target="easy-moderate",
    ),
    exercise(
        "Lat Stretch",
        "stretch",
        "stretch",
        "stretch",
        "bench or rack",
        "static stretch",
        "low",
        "medium",
        "low",
        "low",
        2,
        30,
        45,
        3.0,
        "Open lats and shoulders after pulling.",
        ["shoulders", "stretch"],
        hold_seconds=45,
        side="each side",
        intensity_target="easy",
    ),

    # Cardio / conditioning
    exercise(
        "Incline Walk",
        "conditioning",
        "cardio",
        "cardio",
        "treadmill",
        "cyclical cardio",
        "low",
        "medium",
        "low",
        "low",
        1,
        10,
        20,
        4.0,
        "Easy pace. Nasal breathing if possible.",
        ["cardio", "recovery"],
        duration_minutes=15,
        heart_rate_target="Zone 2 or nasal breathing",
        intensity_target="easy",
    ),
    exercise(
        "Bike",
        "conditioning",
        "cardio",
        "cardio",
        "bike",
        "cyclical cardio",
        "low",
        "medium",
        "low",
        "low",
        1,
        8,
        12,
        5.0,
        "Easy conditioning. Keep it smooth.",
        ["cardio", "recovery"],
        duration_minutes=10,
        heart_rate_target="Zone 2 or nasal breathing",
        intensity_target="easy-moderate",
    ),
    exercise(
        "Row Erg",
        "conditioning",
        "cardio",
        "cardio",
        "rower",
        "cyclical cardio",
        "medium",
        "medium",
        "medium",
        "low",
        1,
        6,
        10,
        6.0,
        "Moderate conditioning. Avoid turning it into a death set.",
        ["cardio", "conditioning"],
        duration_minutes=8,
        heart_rate_target="Zone 2-3",
        intensity_target="moderate",
    ),
]


def get_exercise_catalog() -> list[dict[str, Any]]:
    return [exercise.copy() for exercise in EXERCISE_CATALOG]
