from datetime import datetime

from src.database import (
    init_db,
    seed_setting,
    seed_exercise,
    upsert_progression_state,
)


def seed_settings() -> None:
    settings = {
        "current_bodyweight": "218",
        "goal_bodyweight": "200",
        "unit_weight": "lb",
        "rpe_scale": "10",
        "progression_style": "conservative",
        "lifting_days": "Monday,Wednesday,Saturday",
        "combat_days": "Tuesday,Thursday,Friday,Sunday",
        "primary_goal": "Cut while maintaining strength and improving conditioning",
    }

    for key, value in settings.items():
        seed_setting(key, value)


def seed_exercises() -> None:
    exercises = [
        {
            "exercise_name": "Trap Bar Deadlift",
            "movement_pattern": "hinge",
            "exercise_category": "main_lift",
            "default_sets": 3,
            "default_reps_min": 3,
            "default_reps_max": 5,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Squat",
            "movement_pattern": "squat",
            "exercise_category": "main_lift",
            "default_sets": 3,
            "default_reps_min": 4,
            "default_reps_max": 6,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Bench Press",
            "movement_pattern": "horizontal_push",
            "exercise_category": "main_lift",
            "default_sets": 3,
            "default_reps_min": 4,
            "default_reps_max": 6,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Weighted Pull-Up",
            "movement_pattern": "vertical_pull",
            "exercise_category": "main_lift",
            "default_sets": 3,
            "default_reps_min": 3,
            "default_reps_max": 6,
            "default_rpe": 8.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Pull-Up",
            "movement_pattern": "vertical_pull",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 5,
            "default_reps_max": 10,
            "default_rpe": 8.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Assisted Pull-Up",
            "movement_pattern": "vertical_pull",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 6,
            "default_reps_max": 10,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Landmine Press",
            "movement_pattern": "vertical_push",
            "exercise_category": "secondary_lift",
            "default_sets": 3,
            "default_reps_min": 6,
            "default_reps_max": 10,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Chest-Supported Row",
            "movement_pattern": "horizontal_pull",
            "exercise_category": "secondary_lift",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 8.0,
            "preferred": 1,
        },
        {
            "exercise_name": "DB Row",
            "movement_pattern": "horizontal_pull",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 8.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Goblet Squat",
            "movement_pattern": "squat",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Split Squat",
            "movement_pattern": "single_leg",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Step-Up",
            "movement_pattern": "single_leg",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Back Extension",
            "movement_pattern": "posterior_chain",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 10,
            "default_reps_max": 15,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Romanian Deadlift",
            "movement_pattern": "hinge",
            "exercise_category": "secondary_lift",
            "default_sets": 3,
            "default_reps_min": 6,
            "default_reps_max": 10,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Farmer Carry",
            "movement_pattern": "carry_grip",
            "exercise_category": "gpp",
            "default_sets": 3,
            "default_reps_min": 30,
            "default_reps_max": 60,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Suitcase Carry",
            "movement_pattern": "carry_grip",
            "exercise_category": "gpp",
            "default_sets": 3,
            "default_reps_min": 30,
            "default_reps_max": 60,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Dead Bug",
            "movement_pattern": "core",
            "exercise_category": "recovery_accessory",
            "default_sets": 2,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 5.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Plank",
            "movement_pattern": "core",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 30,
            "default_reps_max": 60,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Hanging Knee Raise",
            "movement_pattern": "core",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "GHR Sit-Up",
            "movement_pattern": "core",
            "exercise_category": "accessory",
            "default_sets": 3,
            "default_reps_min": 8,
            "default_reps_max": 12,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Neck Isometrics",
            "movement_pattern": "neck",
            "exercise_category": "recovery_accessory",
            "default_sets": 2,
            "default_reps_min": 10,
            "default_reps_max": 20,
            "default_rpe": 5.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Wrist Curl",
            "movement_pattern": "forearm_grip",
            "exercise_category": "accessory",
            "default_sets": 2,
            "default_reps_min": 12,
            "default_reps_max": 20,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Reverse Wrist Curl",
            "movement_pattern": "forearm_grip",
            "exercise_category": "accessory",
            "default_sets": 2,
            "default_reps_min": 12,
            "default_reps_max": 20,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Hammer Curl",
            "movement_pattern": "forearm_grip",
            "exercise_category": "accessory",
            "default_sets": 2,
            "default_reps_min": 10,
            "default_reps_max": 15,
            "default_rpe": 7.5,
            "preferred": 1,
        },
        {
            "exercise_name": "Lateral Raise",
            "movement_pattern": "shoulder_accessory",
            "exercise_category": "accessory",
            "default_sets": 2,
            "default_reps_min": 12,
            "default_reps_max": 20,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Triceps Pressdown",
            "movement_pattern": "arm_accessory",
            "exercise_category": "accessory",
            "default_sets": 2,
            "default_reps_min": 10,
            "default_reps_max": 15,
            "default_rpe": 7.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Incline Walk",
            "movement_pattern": "conditioning",
            "exercise_category": "recovery",
            "default_sets": 1,
            "default_reps_min": 10,
            "default_reps_max": 20,
            "default_rpe": 4.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Bike",
            "movement_pattern": "conditioning",
            "exercise_category": "recovery",
            "default_sets": 1,
            "default_reps_min": 10,
            "default_reps_max": 20,
            "default_rpe": 4.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Hip Airplane",
            "movement_pattern": "mobility",
            "exercise_category": "recovery",
            "default_sets": 2,
            "default_reps_min": 5,
            "default_reps_max": 8,
            "default_rpe": 4.0,
            "preferred": 1,
        },
        {
            "exercise_name": "Mobility Flow",
            "movement_pattern": "mobility",
            "exercise_category": "recovery",
            "default_sets": 1,
            "default_reps_min": 5,
            "default_reps_max": 10,
            "default_rpe": 3.0,
            "preferred": 1,
        },
    ]

    for exercise in exercises:
        seed_exercise(exercise)


def seed_progression_state() -> None:
    now = datetime.now().isoformat()

    progression_items = [
        {
            "exercise_name": "Trap Bar Deadlift",
            "movement_pattern": "hinge",
            "exercise_category": "main_lift",
            "current_training_load": 300,
            "target_sets": 3,
            "target_reps_min": 3,
            "target_reps_max": 5,
            "last_successful_load": 300,
            "performance_credit": 0,
            "estimated_1rm": 375,
            "next_recommended_load": 300,
            "last_updated": now,
        },
        {
            "exercise_name": "Bench Press",
            "movement_pattern": "horizontal_push",
            "exercise_category": "main_lift",
            "current_training_load": 195,
            "target_sets": 3,
            "target_reps_min": 4,
            "target_reps_max": 6,
            "last_successful_load": 195,
            "performance_credit": 0,
            "estimated_1rm": 245,
            "next_recommended_load": 195,
            "last_updated": now,
        },
        {
            "exercise_name": "Squat",
            "movement_pattern": "squat",
            "exercise_category": "main_lift",
            "current_training_load": 275,
            "target_sets": 3,
            "target_reps_min": 4,
            "target_reps_max": 6,
            "last_successful_load": 275,
            "performance_credit": 0,
            "estimated_1rm": 365,
            "next_recommended_load": 275,
            "last_updated": now,
        },
        {
            "exercise_name": "Weighted Pull-Up",
            "movement_pattern": "vertical_pull",
            "exercise_category": "main_lift",
            "current_training_load": 25,
            "target_sets": 3,
            "target_reps_min": 3,
            "target_reps_max": 6,
            "last_successful_load": 25,
            "performance_credit": 0,
            "estimated_1rm": 45,
            "next_recommended_load": 25,
            "last_updated": now,
        },
    ]

    for item in progression_items:
        upsert_progression_state(item)


def seed_all() -> None:
    init_db()
    seed_settings()
    seed_exercises()
    seed_progression_state()
